# Generated by Django 5.2.3 on 2025-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjournal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
