services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./backend:/app
