/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignUpRequestDTO"];
                    "text/json": components["schemas"]["SignUpRequestDTO"];
                    "application/*+json": components["schemas"]["SignUpRequestDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignInRequestDTO"];
                    "text/json": components["schemas"]["SignInRequestDTO"];
                    "application/*+json": components["schemas"]["SignInRequestDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponseDTO"];
                        "application/json": components["schemas"]["TokenResponseDTO"];
                        "text/json": components["schemas"]["TokenResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponseDTO"];
                        "application/json": components["schemas"]["TokenResponseDTO"];
                        "text/json": components["schemas"]["TokenResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetCalendarDTO"][];
                        "application/json": components["schemas"]["GetCalendarDTO"][];
                        "text/json": components["schemas"]["GetCalendarDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarDTO"];
                    "text/json": components["schemas"]["CreateCalendarDTO"];
                    "application/*+json": components["schemas"]["CreateCalendarDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/CalendarEntry/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetCalendarEntryDTO"][];
                        "application/json": components["schemas"]["GetCalendarEntryDTO"][];
                        "text/json": components["schemas"]["GetCalendarEntryDTO"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/CalendarEntry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCalendarEntryDTO"];
                    "text/json": components["schemas"]["UpdateCalendarEntryDTO"];
                    "application/*+json": components["schemas"]["UpdateCalendarEntryDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarEntryDTO"];
                    "text/json": components["schemas"]["CreateCalendarEntryDTO"];
                    "application/*+json": components["schemas"]["CreateCalendarEntryDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetProfileDto"];
                        "application/json": components["schemas"]["GetProfileDto"];
                        "text/json": components["schemas"]["GetProfileDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/SharedCalendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSharedCalendarDTO"];
                    "text/json": components["schemas"]["CreateSharedCalendarDTO"];
                    "application/*+json": components["schemas"]["CreateSharedCalendarDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCalendarDTO: {
            name?: string | null;
            /** Format: int32 */
            color?: number;
        };
        CreateCalendarEntryDTO: {
            entryCategory?: components["schemas"]["EntryCategory"];
            name?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string | null;
            location?: string | null;
            /** Format: date-time */
            notificationTime?: string | null;
            /** Format: int32 */
            color?: number;
            /** Format: uuid */
            calendarId?: string;
            /** Format: uuid */
            createdBy?: string;
        };
        CreateSharedCalendarDTO: {
            /** Format: uuid */
            calendarId?: string;
            role?: components["schemas"]["Role"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        EntryCategory: 0 | 1 | 2 | 3 | 4;
        GetCalendarDTO: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            color?: number;
        };
        GetCalendarEntryDTO: {
            /** Format: uuid */
            id?: string;
            entryCategory?: components["schemas"]["EntryCategory"];
            name?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string | null;
            location?: string | null;
            /** Format: date-time */
            notificationTime?: string | null;
            /** Format: int32 */
            color?: number;
            isCompleted?: boolean | null;
            /** Format: uuid */
            calendarId?: string;
            /** Format: uuid */
            createdBy?: string;
        };
        GetProfileDto: {
            /** Format: uuid */
            id?: string;
            username?: string | null;
            avatar?: string | null;
            isPrivate?: boolean;
            firstName?: string | null;
            lastName?: string | null;
            /** Format: date */
            birthDate?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        Role: 0 | 1;
        SignInRequestDTO: {
            email?: string | null;
            password?: string | null;
        };
        SignUpRequestDTO: {
            email?: string | null;
            password?: string | null;
        };
        TokenResponseDTO: {
            accessToken: string | null;
            refreshToken: string | null;
        };
        UpdateCalendarEntryDTO: {
            entryCategory?: components["schemas"]["EntryCategory"];
            name?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string | null;
            location?: string | null;
            /** Format: date-time */
            notificationTime?: string | null;
            /** Format: int32 */
            color?: number;
            isCompleted?: boolean | null;
            /** Format: uuid */
            createdBy?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
